version: 0.0
os: windows
files:
  - source: /output
    destination: C:\inetpub\wwwroot\MyApp
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.ps1
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: scripts/AfterInstall.ps1
      timeout: 300
      runas: Administrator
  ApplicationStart:
    - location: scripts/ApplicationStart.ps1
      timeout: 300
      runas: Administrator
  ValidateService:
    - location: scripts/ValidateService.ps1
      timeout: 300
      runas: Administrator
